#server:
#  port: 8080
#  servlet:
#    context-path: /doan
#
#spring:
#  datasource:
#    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/doan}
#    driverClassName: "com.mysql.cj.jdbc.Driver"
#    username: ${DBMS_USERNAME:root}
#    password: ${DBMS_PASSWORD:19681902}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: false
#
#app:
#  file:
#    storage-dir: F:/upload
#
#jwt:
#  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
#  valid-duration: 3600 # in second
#  refreshable-duration: 3600 # in seconds